# Generated by Django 5.2.8 on 2025-11-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='session_state',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='coachnote',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_notes', to='coaching.coachingsession'),
        ),
    ]
