# Generated by Django 5.2.8 on 2025-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_coachingsession_session_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingexercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coachingexercise',
            name='estimated_duration',
            field=models.IntegerField(default=5, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='coachingexercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coachingexercise',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coachingrecommendation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
